server.port=${PORT:8082}
spring.application.name=events-service

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_null

events.kafka.brokers=${KAFKA_BROKERS:localhost:9092}
events.kafka.consumer-group=events-service

logging.level.org.apache.kafka=WARN
